language: python

train_version: 1.0

tools:
   - msde/git/2.9.5
   - python/core/2.7.9-64
   - msde/msdlbuild/prod

build_types:
   - build_type:
      name: release
      build:
         - script: msdlbuild clean
         - script: make clean
         - script: make install
         - script: msdlbuild metadata

test_types:
    - test_type:
         name: all
         test: set -o pipefail; ./tests/runtests.py --config=./tests/unittest.conf --no-interactive | tee ./tests/aqdtests.log
    - test_type:
         name: failfast
         test: set -o pipefail; ./tests/runtests.py --config=./tests/unittest.conf --failfast --no-interactive | tee ./tests/aqdtests.log
    - test_type:
         name: restart
         test: ./tests/restarttests.sh
    - test_type:
         name: jenkins
         test: ./tests/jenkinstest.sh
